const genreData = {
        genreName: {
            action: "Action",
            strategy: "Strategy",
            sports: "Sports",
            adventure: "Adventure",
            "role-playing": "Role-Playing",
            "driving-racing": "Driving/Racing",
            simulation: "Simulation",
            educational: "Educational",
            fighting: "Fighting",
            wrestling: "Wrestling",
            shooter: "Shooter",
            "real-time-strategy": "Real-Time Strategy",
            "card-game": "Card Game",
            "trivia-board-game": "Trivia/Board Game",
            mmorpg: "MMORPG",
            "minigame-collection": "Minigame Collection",
            puzzle: "Puzzle",
            music: "Music/Rhythm",
            boxing: "Boxing",
            football: "Football",
            basketball: "Basketball",
            skateboarding: "Skateboarding",
            "flight-simulator": "Flight Simulator",
            fishing: "Fishing",
            golf: "Golf",
            "first-person-shooter": "First-Person Shooter",
            fps: "First-Person Shooter",
            snowboarding: "Snowboarding/Skiing",
            skiing: "Snowboarding/Skiing",
            baseball: "Baseball",
            "vehicular-combat": "Vehicular Combat",
            hockey: "Hockey",
            soccer: "Soccer",
            platformer: "Platformer",
            "action-adventure": "Action-Adventure",
            fitness: "Fitness",
            "block-breaking": "Block-Breaking",
            moba: "MOBA"
        }
    };